### ISSUE TITLE
Can't find the dependency of the latest version from JitPack.

### ISSUE THREAD

**Issue by RE4ERKA** [Odalita-Developments/OdalitaMenus#16]
```
Could not determine the dependencies of task ':shadowJar'.
> Could not resolve all dependencies for configuration ':runtimeClasspath'.
   > Could not find com.github.odalita-developments.odalitamenus:core:v0.5.7.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/odalita-developments/odalitamenus/core/v0.5.7/core-v0.5.7.pom
       - https://repo.papermc.io/repository/maven-public/com/github/odalita-developments/odalitamenus/core/v0.5.7/core-v0.5.7.pom
       - https://repo.aikar.co/content/groups/aikar/com/github/odalita-developments/odalitamenus/core/v0.5.7/core-v0.5.7.pom
       - https://jitpack.io/com/github/odalita-developments/odalitamenus/core/v0.5.7/core-v0.5.7.pom
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
 ```

**Comment by TryDev07** [comment]
Hello,

Thank you for your bug report. I have released a new version on JitPack, which should resolve the dependency issue. Please let me know if the problem persists.

**Comment by CamChuaVN** [comment]
> Hello,
> 
> Thank you for your bug report. I have released a new version on JitPack, which should resolve the dependency issue. Please let me know if the problem persists.

its seem like not working yet

**Comment by TryDev07** [comment]
What does it tell you? Because i tried the dependency on a project and for me it found the dependency

**Comment by CamChuaVN** [comment]
> What does it tell you? Because i tried the dependency on a project and for me it found the dependency

Its say like the above
`ChunkCollector:main: Could not find com.github.odalita-developments.odalitamenus:core:v0.5.7.
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/com/github/odalita-developments/odalitamenus/core/v0.5.7/core-v0.5.7.pom
  - https://repo.papermc.io/repository/maven-public/com/github/odalita-developments/odalitamenus/core/v0.5.7/core-v0.5.7.pom
  - https://repo.codemc.io/repository/maven-public/com/github/odalita-developments/odalitamenus/core/v0.5.7/core-v0.5.7.pom
  - https://repo.codemc.org/repository/maven-public/com/github/odalita-developments/odalitamenus/core/v0.5.7/core-v0.5.7.pom
  - https://s01.oss.sonatype.org/content/repositories/snapshots/com/github/odalita-developments/odalitamenus/core/v0.5.7/core-v0.5.7.pom
  - https://jitpack.io/com/github/odalita-developments/odalitamenus/core/v0.5.7/core-v0.5.7.pom
  - https://repo.dmulloy2.net/repository/public/com/github/odalita-developments/odalitamenus/core/v0.5.7/core-v0.5.7.pom
Required by:
    project :`

**Comment by RE4ERKA** [comment]
Me too, I still can't find the dependency.

It works:
https://jitpack.io/com/github/odalita-developments/odalitamenus/core/v0.5.6/core-v0.5.6.pom
Doesn't work:
https://jitpack.io/com/github/odalita-developments/odalitamenus/core/v0.5.7/core-v0.5.7.pom

**Comment by TryDev07** [comment]
i check it on both gradle and maven and both work fine for me?
Maby you can try to invalidate caches in intelijk.

![image](https://github.com/Odalita-Developments/OdalitaMenus/assets/58628969/45f652c5-0e0d-41d5-a5df-e7744d30ac73)

**Comment by RE4ERKA** [comment]
The problem is the case. You have a dependency link like this on your Github home page:
```
    implementation 'com.github.odalita-developments.odalitamenus:core:v0.5.7'
```

That's what we're trying to hook it up to, all lowercase.

If we try to connect the dependency in case like you have in your screenshot, it will work.
```
    implementation 'com.github.Odalita-Developments.OdalitaMenus:core:v0.5.7'
```

Please fix the case on the main Github page.
![image](https://github.com/Odalita-Developments/OdalitaMenus/assets/66727581/eeb7e556-023a-4662-bb2b-8c60d917de9e)

**Comment by TryDev07** [comment]
Alright, I will update the dependencies listed on the homepage to the correct ones. I'm glad it's working for you now!

**Comment by CamChuaVN** [comment]
> Alright, I will update the dependencies listed on the homepage to the correct ones. I'm glad it's working for you now!

btw you should note that it should be core not common well if we use common library it will not found OdalitaMenus class 
![image](https://github.com/Odalita-Developments/OdalitaMenus/assets/32415041/73308d7f-dae7-4ef2-8956-9600e8de4aa1)

**Comment by ItzKiwiSap** [comment]
> The problem is the letter case. You have a dependency link like this on your Github home page:
> 
> ```
>     implementation 'com.github.odalita-developments.odalitamenus:core:v0.5.7'
> ```
> 
> That's what we're trying to hook it up to, all lowercase.
> 
> If we try to connect the dependency in case like you have in your screenshot, it will work.
> 
> ```
>     implementation 'com.github.Odalita-Developments.OdalitaMenus:core:v0.5.7'
> ```
> 
> Please fix the case on the main Github page. ![image](https://private-user-images.githubusercontent.com/66727581/344486091-eeb7e556-023a-4662-bb2b-8c60d917de9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NzMzMjAsIm5iZiI6MTcxOTc3MzAyMCwicGF0aCI6Ii82NjcyNzU4MS8zNDQ0ODYwOTEtZWViN2U1NTYtMDIzYS00NjYyLWJiMmItOGM2MGQ5MTdkZTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDE4NDM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzZDA5OGQzN2E5NGVjYWQ0ZWU4ZWFiYjk3Y2IwYWQ5YjQ5ZGJlZGM3ZmM5YjAyMTI3N2YzOWM2MmRiNzViOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HZ9gGNL4LLU54JAKyC1byUqpPNMuOtpfkKI8ng6U7KY)

The letter case doesn't matter, you have the lowercase locally cached as a failure. If you delete the cache for version v0.5.7 it will work with lowercase.

**Comment by CamChuaVN** [comment]
> > The problem is the letter case. You have a dependency link like this on your Github home page:
> > ```
> >     implementation 'com.github.odalita-developments.odalitamenus:core:v0.5.7'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That's what we're trying to hook it up to, all lowercase.
> > If we try to connect the dependency in case like you have in your screenshot, it will work.
> > ```
> >     implementation 'com.github.Odalita-Developments.OdalitaMenus:core:v0.5.7'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please fix the case on the main Github page. ![image](https://private-user-images.githubusercontent.com/66727581/344486091-eeb7e556-023a-4662-bb2b-8c60d917de9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NzMzMjAsIm5iZiI6MTcxOTc3MzAyMCwicGF0aCI6Ii82NjcyNzU4MS8zNDQ0ODYwOTEtZWViN2U1NTYtMDIzYS00NjYyLWJiMmItOGM2MGQ5MTdkZTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDE4NDM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzZDA5OGQzN2E5NGVjYWQ0ZWU4ZWFiYjk3Y2IwYWQ5YjQ5ZGJlZGM3ZmM5YjAyMTI3N2YzOWM2MmRiNzViOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HZ9gGNL4LLU54JAKyC1byUqpPNMuOtpfkKI8ng6U7KY)
> 
> The letter case doesn't matter, you have the lowercase locally cached as a failure. If you delete the cache for version v0.5.7 it will work with lowercase.

where the cache you delete?

**Comment by TryDev07** [comment]
> > > The problem is the letter case. You have a dependency link like this on your Github home page:
> > > ```
> > >     implementation 'com.github.odalita-developments.odalitamenus:core:v0.5.7'
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > That's what we're trying to hook it up to, all lowercase.
> > > If we try to connect the dependency in case like you have in your screenshot, it will work.
> > > ```
> > >     implementation 'com.github.Odalita-Developments.OdalitaMenus:core:v0.5.7'
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Please fix the case on the main Github page. ![image](https://private-user-images.githubusercontent.com/66727581/344486091-eeb7e556-023a-4662-bb2b-8c60d917de9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NzMzMjAsIm5iZiI6MTcxOTc3MzAyMCwicGF0aCI6Ii82NjcyNzU4MS8zNDQ0ODYwOTEtZWViN2U1NTYtMDIzYS00NjYyLWJiMmItOGM2MGQ5MTdkZTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDE4NDM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzZDA5OGQzN2E5NGVjYWQ0ZWU4ZWFiYjk3Y2IwYWQ5YjQ5ZGJlZGM3ZmM5YjAyMTI3N2YzOWM2MmRiNzViOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HZ9gGNL4LLU54JAKyC1byUqpPNMuOtpfkKI8ng6U7KY)
> > 
> > 
> > The letter case doesn't matter, you have the lowercase locally cached as a failure. If you delete the cache for version v0.5.7 it will work with lowercase.
> 
> where the cache you delete?

For maven i beleve you just have to add the -u flag like this:
`mvn -U clean install`

For gradle it should be something like this:
`./gradlew build --refresh-dependencies`
https://docs.gradle.org/current/userguide/dynamic_versions.html#sec:controlling_dependency_caching_command_line

**Comment by CamChuaVN** [comment]
> > > > The problem is the letter case. You have a dependency link like this on your Github home page:
> > > > ```
> > > >     implementation 'com.github.odalita-developments.odalitamenus:core:v0.5.7'
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > That's what we're trying to hook it up to, all lowercase.
> > > > If we try to connect the dependency in case like you have in your screenshot, it will work.
> > > > ```
> > > >     implementation 'com.github.Odalita-Developments.OdalitaMenus:core:v0.5.7'
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Please fix the case on the main Github page. ![image](https://private-user-images.githubusercontent.com/66727581/344486091-eeb7e556-023a-4662-bb2b-8c60d917de9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NzMzMjAsIm5iZiI6MTcxOTc3MzAyMCwicGF0aCI6Ii82NjcyNzU4MS8zNDQ0ODYwOTEtZWViN2U1NTYtMDIzYS00NjYyLWJiMmItOGM2MGQ5MTdkZTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDE4NDM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzZDA5OGQzN2E5NGVjYWQ0ZWU4ZWFiYjk3Y2IwYWQ5YjQ5ZGJlZGM3ZmM5YjAyMTI3N2YzOWM2MmRiNzViOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HZ9gGNL4LLU54JAKyC1byUqpPNMuOtpfkKI8ng6U7KY)
> > > 
> > > 
> > > The letter case doesn't matter, you have the lowercase locally cached as a failure. If you delete the cache for version v0.5.7 it will work with lowercase.
> > 
> > 
> > where the cache you delete?
> 
> For maven i beleve you just have to add the -u flag like this: `mvn -U clean install`
> 
> For gradle it should be something like this: `./gradlew build --refresh-dependencies` https://docs.gradle.org/current/userguide/dynamic_versions.html#sec:controlling_dependency_caching_command_line

that seem didn't work for me well i should stick at letter case
