### ISSUE TITLE
1.20.2 Support

### ISSUE THREAD

**Issue by killertuling** [Odalita-Developments/OdalitaMenus#17]
it not work on 1.20.2...Can we continue to support 1.20.2 in the future? Due to some legacy reasons, a small number of people are still using 1.20.2
![be86194fa4605a13698d5bbedac0c1b9](https://github.com/user-attachments/assets/cca57c8f-c604-46b2-ac37-04873efdccb6)

**Comment by ItzKiwiSap** [comment]
Hi, thanks for letting us know, I'll add it again!
