### ISSUE TITLE
Dependecy not found

### ISSUE THREAD

**Issue by thelipe7** [Odalita-Developments/OdalitaMenus#19]
The dependency is not being found:
![image](https://github.com/user-attachments/assets/28bc9afb-8406-4576-a95c-5337cd371dd9)

**Comment by ItzKiwiSap** [comment]
Hi, sorry for the late response, I'm currently on holiday. Does 0.5.9 work? I'll take a look at it when I'm back. In the meantime you could clone the project and build it yourself and use mavenLocal.

**Comment by thelipe7** [comment]
Good evening, I've just tested both 0.5.10 and 0.5.9 and they both didn't work.

**Comment by ItzKiwiSap** [comment]
Hi, I now use maven central to publish, which should resolve this issue. Could you try using the new dependency for 0.5.11 and let me know if it works?
